---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgAO7kBvNVI+R77VRw0tuufwe55pyGpJ0OpwgdY9ymnc83mNTUGLFuU8QFf/OgTTjepT6/F1bJfQfgCteYIresE/U9epvnw4EW65rLKxfRLydQ/cm2HZ3WvClPvNA7b9p6qXdj04RdH8g0sjQ+eSMbCcw5h5efBTjNgjtXus7nZ8YPMvT3MvcRR55z96xIINm9l7bUvvt1BdsVnS1ybbD2CX9Yj8pJmblsaZoo4cgU56nhGLL4sQZWxdgMbgVb3kLAEFuD2ih1Mn88w68Sl2XJ/VttTS1X9QtxjRfamuVyUq0PFm6QIBQcj+l6sFL48ZQe9EOJ9BBQcXMLpHtRJyQPhm4NPH3iGNf1AYa6p4mK5+QHyLLnpLm6nBbE2KCVmUi/Q+piK/UGL8eU1Gmvjz+tqeM9q1754d2IHlRkiG9xQcYKddz7+OyIE8zLQNAM9eyJWH0HiRZM9XoEl8jjL8FghO5PYeFJIWpQTJ1aceQvuJBRcK4oi86s4ywaP0RWrlOiO2lw1arNCAWTmS4TLfJZD1A6o+GDVCvyAGpJCNGdR/HFuig3IFTtsUjYztS9HmdgOrlU+cI+y6wh2g4HLeNrY+spHdwKA7sVf8mk3P2o2L4nHi5Xz/3UY/wgXwSBYkptTyAqI4eZ28H5ge0YR/f837Vf+3+XCLrygVhuAWCkgEiIKB99eF4vSjQ1l9bvnMEb7AJpzxhqvyoueVcC+hxxbYqq7PwQzTs9dtwKgwaWQVJN93+no9m1s=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
